---
name: 🖥️ Inventory request
description: Modify inventory (add, update or delete) groups/hosts/variables
title: '🖥️ INVENTORY - `Enter issue title`'
labels: ['automation', 'tech/tech-repo', 'kind/inventory']
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Remember that an Inventory request is used to modify the Ansible inventory structure.
        > This can include adding new groups or hosts, updating existing variables, or deleting obsolete entries
  - type: checkboxes
    id: environments
    attributes:
      label: Affected environments
      description: Select all that apply
      options:
        - label: Production
        - label: Pre-production
        - label: Development
    validations:
      required: true
  - type: textarea
    id: Description
    attributes:
      label: "Description"
      placeholder: >
        ❗❗❗ PLEASE REMOVE `` CHARACTERS FROM TITLE AND REPLACE WITH PROPER VALUES ❗❗❗

        A clear and concise description of what changes must be modified, added or deleted.

        Example:
          - Add new group and hosts for new XXXX Aplication
          - Add new variable on xxxx group vars for xxxxx
          - Update variable on xxxx group vars for xxxxx
